[package]
name = "arkrail_guardian"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rust-embed = "8.7.2"
sysinfo = "0.36.0"


[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
